import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const pushAction = fs.readFileSync(new URL('../app/actions/push.ts', import.meta.url), 'utf8')
const pushModule = fs.readFileSync(new URL('../lib/push-notifications.ts', import.meta.url), 'utf8')
const pushClient = fs.readFileSync(new URL('../lib/push-client.ts', import.meta.url), 'utf8')
const pwaShell = fs.readFileSync(new URL('../components/pwa-shell.tsx', import.meta.url), 'utf8')
const loginPage = fs.readFileSync(new URL('../app/login/page.tsx', import.meta.url), 'utf8')
const serviceWorker = fs.readFileSync(new URL('../public/sw.js', import.meta.url), 'utf8')
const closingsAction = fs.readFileSync(new URL('../app/actions/closings.ts', import.meta.url), 'utf8')
const ckAction = fs.readFileSync(new URL('../app/actions/ck.ts', import.meta.url), 'utf8')
const managerNav = fs.readFileSync(new URL('../components/manager/nav.tsx', import.meta.url), 'utf8')
const hqNav = fs.readFileSync(new URL('../components/hq/nav.tsx', import.meta.url), 'utf8')
const migration = fs.readFileSync(new URL('../supabase/migrations/069_push_subscriptions.sql', import.meta.url), 'utf8')
const controlsMigration = fs.readFileSync(new URL('../supabase/migrations/070_push_notification_controls.sql', import.meta.url), 'utf8')
const centerMigration = fs.readFileSync(new URL('../supabase/migrations/071_push_notification_center.sql', import.meta.url), 'utf8')
const pushManagementAction = fs.readFileSync(new URL('../app/actions/push-management.ts', import.meta.url), 'utf8')
const notificationActions = fs.readFileSync(new URL('../app/actions/notifications.ts', import.meta.url), 'utf8')
const notificationCenter = fs.readFileSync(new URL('../components/notification-center.tsx', import.meta.url), 'utf8')
const pushAdminPage = fs.readFileSync(new URL('../app/hq/notifications/page.tsx', import.meta.url), 'utf8')
const storeEditor = fs.readFileSync(new URL('../components/hq/store-editor.tsx', import.meta.url), 'utf8')
const userEditor = fs.readFileSync(new URL('../components/hq/user-edit-dialog.tsx', import.meta.url), 'utf8')
const storesPage = fs.readFileSync(new URL('../app/hq/stores/page.tsx', import.meta.url), 'utf8')
const usersPage = fs.readFileSync(new URL('../app/hq/users/page.tsx', import.meta.url), 'utf8')
const userCreateDialog = fs.readFileSync(new URL('../components/hq/user-create-dialog.tsx', import.meta.url), 'utf8')
const pushPreferences = fs.readFileSync(new URL('../lib/push-preferences.ts', import.meta.url), 'utf8')

test('推播訂閱只能由登入者管理自己的裝置', () => {
  assert.match(pushAction, /const user = await getVerifiedUser\(\)/)
  assert.match(pushAction, /\.eq\('user_id', user\.id\)/)
  assert.match(migration, /alter table push_subscriptions enable row level security/)
  assert.match(migration, /using \(user_id = auth\.uid\(\)\)/)
  assert.match(migration, /revoke all on table push_subscriptions from anon/)
})

test('手機須由使用者點擊後才要求推播權限並建立訂閱', () => {
  assert.match(pwaShell, /onClick=\{enable\}/)
  assert.match(pwaShell, /Notification\.requestPermission\(\)/)
  assert.match(pushClient, /pushManager\.subscribe\(/)
  assert.match(pwaShell, /if \(!isRunningStandalone\(\)\) return/)
  assert.match(pwaShell, /pathname\.startsWith\('\/manager\/'\) \|\| pathname\.startsWith\('\/hq\/'\)/)
})

test('Service Worker 顯示通知並可前往對應帳目', () => {
  assert.match(serviceWorker, /addEventListener\('push'/)
  assert.match(serviceWorker, /showNotification\(title/)
  assert.match(serviceWorker, /addEventListener\('notificationclick'/)
  assert.match(serviceWorker, /client\.navigate\(destination\)/)
  assert.match(serviceWorker, /notificationId/)
  assert.match(serviceWorker, /\/api\/notifications\/click/)
})

test('店面與央廚送審及審核結果都會在回應後發送推播', () => {
  assert.match(closingsAction, /notifyReviewersOfSubmission\(\{\s*kind: 'store'/)
  assert.match(closingsAction, /notifyStoreUsersOfReview\(\{\s*kind: 'store'/)
  assert.match(ckAction, /notifyReviewersOfSubmission\(\{\s*kind: 'ck'/)
  assert.match(ckAction, /notifyStoreUsersOfReview\(\{\s*kind: 'ck'/)
  assert.match(pushModule, /canReviewClosings\(profile as PermissionProfile\)/)
  assert.match(pushModule, /\.eq\('status', 'submitted'\)\.eq\('business_date', input\.businessDate\)/)
  assert.match(pushModule, /該營業日目前共有/)
  assert.doesNotMatch(pushModule, /review_note|dispute_note/)
})

test('帳目退回後重新送出會建立新的待審推播事件', () => {
  assert.match(pushModule, /submissionEventId: string/)
  assert.match(pushModule, /sourceKey: `\$\{input\.kind\}-submission-\$\{input\.recordId\}-\$\{input\.submissionEventId\}`/)
  assert.match(pushModule, /退回帳目已重新送出/)
  assert.match(pushModule, /已修正並重新送出/)
  assert.match(closingsAction, /submissionEventId: submittedAt/)
  assert.match(closingsAction, /wasReturned: meta\.status === 'disputed'/)
  assert.match(ckAction, /submissionEventId,\s*wasReturned/)
  assert.match(ckAction, /wasReturned: previousStatus === 'disputed'/)
  assert.match(serviceWorker, /renotify: true/)
})

test('同一裝置切換到總公司帳號時會重新綁定並補發待審摘要', () => {
  assert.match(pushAction, /existing\.user_id !== user\.id/)
  assert.match(pushAction, /notifyReviewerOfPendingWork\(user\.id\)/)
  assert.match(pushModule, /export async function notifyReviewerOfPendingWork/)
  assert.match(pushModule, /有帳目等待審核/)
  assert.match(pushModule, /const businessDate = getBusinessDate\(\)/)
  assert.match(pushModule, /\.eq\('status', 'submitted'\)\.eq\('business_date', businessDate\)/)
  assert.match(managerNav, /await detachPushSubscriptionFromCurrentUser\(\)/)
  assert.match(hqNav, /await detachPushSubscriptionFromCurrentUser\(\)/)
  assert.match(loginPage, /await syncPushSubscriptionToCurrentUser\(/)
  assert.match(pwaShell, /window\.addEventListener\('focus', sync\)/)
  assert.match(pwaShell, /document\.addEventListener\('visibilitychange', onVisible\)/)
  assert.match(pwaShell, /result\.reassigned\) router\.refresh\(\)/)
})

test('失效的裝置訂閱會自動移除', () => {
  assert.match(pushModule, /statusCode === 404 \|\| statusCode === 410/)
  assert.match(pushModule, /from\('push_subscriptions'\)\.delete\(\)\.eq\('id', subscription\.id\)/)
})

test('總公司可分別控制店家與帳號推播', () => {
  assert.match(controlsMigration, /alter table stores[\s\S]*push_notifications_enabled boolean not null default true/)
  assert.match(controlsMigration, /alter table user_profiles[\s\S]*push_notifications_enabled boolean not null default true/)
  assert.match(pushModule, /profile\.push_notifications_enabled !== false/)
  assert.match(pushModule, /store\?\.push_notifications_enabled !== false/)
  assert.match(centerMigration, /push_notification_preferences jsonb not null default/)
  assert.match(pushModule, /preferenceEnabled\(profile\.push_notification_preferences, options\.category\)/)
  assert.match(userEditor, /pushPreferenceOptionsForUnit/)
  assert.match(storeEditor, /push_notification_preferences: pushPreferences/)
  assert.match(storeEditor, /接收帳務提醒與審核結果通知/)
  assert.match(userEditor, /接收帳務推播/)
})

test('推播選項會依總公司、店面與央廚身分分流', () => {
  assert.match(pushPreferences, /hq: \['review_submission', 'hq_escalation'\]/)
  assert.match(pushPreferences, /store: \['review_result', 'accounting_reminder'\]/)
  assert.match(pushPreferences, /ck: \['review_result', 'accounting_reminder', 'reimbursement_handoff'\]/)
  assert.match(userEditor, /pushPreferenceOptionsForUnit\(unitType\)/)
  assert.match(userEditor, /scopePushPreferencesForUnit\(form\.push_notification_preferences, unitType\)/)
  assert.match(userCreateDialog, /defaultPushPreferencesForUnit\(unitType\)/)
  assert.match(pushModule, /profile\.role !== '老闆' && profile\.is_hq !== true/)
})

test('管理頁顯示綁定裝置數並可發送測試通知', () => {
  assert.match(storesPage, /pushDeviceCountByStore/)
  assert.match(usersPage, /pushDeviceCountByUser/)
  assert.match(storeEditor, /sendStorePushTest/)
  assert.match(userEditor, /sendUserPushTest/)
  assert.match(pushManagementAction, /canManageUsers\(profile\)/)
  assert.match(pushManagementAction, /canManageCKSettings\(profile\)/)
  assert.match(pushManagementAction, /canManageStoreSettings\(profile\)/)
})

test('系統保留通知紀錄、未讀狀態與每台裝置的投遞工作', () => {
  assert.match(centerMigration, /create table if not exists app_notifications/)
  assert.match(centerMigration, /create table if not exists push_delivery_jobs/)
  assert.match(centerMigration, /unique \(user_id, source_key\)/)
  assert.match(centerMigration, /app_notifications_select_own/)
  assert.match(pushModule, /from\('app_notifications'\)[\s\S]*\.upsert/)
  assert.match(pushModule, /from\('push_delivery_jobs'\)\.upsert/)
  assert.match(notificationActions, /export async function getMyNotifications/)
  assert.match(notificationActions, /export async function markAllNotificationsRead/)
  assert.match(notificationCenter, /通知中心/)
  assert.match(notificationCenter, /30_?000|30000/)
})

test('推播失敗會重試三次並在後台顯示裝置與失敗原因', () => {
  assert.match(pushModule, /attemptCount < 3/)
  assert.match(pushModule, /attemptCount === 1 \? 5 : 15/)
  assert.match(pushModule, /export async function processPendingPushJobs/)
  assert.match(centerMigration, /last_error text/)
  assert.match(centerMigration, /last_seen_at timestamptz/)
  assert.match(pushAdminPage, /最近推播紀錄/)
  assert.match(pushAdminPage, /失敗原因/)
  assert.match(pushManagementAction, /export async function removeUserPushDevice/)
  assert.match(pushAdminPage, /PushDeviceRemoveButton/)
})
