import type { AuditChange } from '@/lib/audit-metadata'

export const AUDIT_METADATA_LABELS: Record<string, string> = {
  action: '執行動作',
  entity: '操作對象',
  entity_type: '資料類型',
  entity_id: '資料編號',
  id: '編號',
  type: '資料類型',
  name: '名稱',
  user_id: '使用者編號',
  manager_id: '店長編號',
  closing_id: '帳目編號',
  receipt_id: '收據編號',
  original_closing_id: '原帳目編號',
  business_date: '帳目日期',
  month: '月份',
  vendor: '廠商／分類',
  vendor_name: '廠商／分類',
  actual_vendor_name: '實際廠商',
  receipt_type: '單據類型',
  amount: '金額',
  total_amount: '單據總額',
  tax_amount: '稅額',
  old_price: '原單價',
  new_price: '新單價',
  note: '備註',
  notes: '備註',
  reason: '原因',
  status: '狀態',
  review_status: '審核狀態',
  previous_status: '原狀態',
  decision: '審核結果',
  before: '修改前',
  after: '修改後',
  changes: '變更欄位',
  items: '品項明細',
  receipt_items: '收據品項',
  revenue_items: '營收明細',
  cash_counts: '現金清點',
  expense_items: '費用明細',
  order_items: '叫貨明細',
  handwrite_orders: '手寫訂單',
  platform_screenshots: '平台截圖',
  receipts: '單據明細',
  expenses: '支出明細',
  category: '分類',
  item_name: '品項名稱',
  item_category: '品項分類',
  excel_column: '報表欄位',
  doc_type: '單據類型',
  payer_name: '付款人',
  vendor_group: '廠商分類',
  quantity: '數量',
  unit: '單位',
  unit_price: '單價',
  member_orders: '體系內店家金額',
  external_orders: '體系外店家金額',
  external_store_id: '體系外店家編號',
  external_store_name: '體系外店家名稱',
  confirmed_amount: '央廚確認金額',
  delivery_photo_source: '配送照片來源',
  delivery_photo_count: '配送單照片數',
  transfer_photo_required: '需轉帳照片',
  transfer_photo_count: '轉帳照片數',
  has_external: '包含體系外叫貨',
  has_expenses: '包含支出明細',
  has_receipt_photo: '已附單據照片',
  has_photo: '已附照片',
  receipt_photo_count: '單據照片數',
  photo_count: '照片數',
  assigned_store_id: '指派店家',
  assigned_store_ids: '指派店家',
  store_id: '店家',
  store_ids: '店家',
  primary_store_id: '主要店家',
  role: '系統角色',
  title: '職稱',
  employee_id: '員工編號',
  is_hq: '總公司身分',
  active: '啟用狀態',
  account: '登入帳號',
  account_created: '帳號已建立',
  password_changed: '密碼已變更',
  password_value: '密碼內容',
  can_manage_users: '可管理人員',
  can_manage_stores: '可管理店家',
  can_manage_store_settings: '可管理店面設定',
  can_manage_ck_settings: '可管理央廚設定',
  can_manage_items: '可管理品項',
  can_manage_store_items: '可管理店面品項',
  can_manage_ck_items: '可管理央廚品項',
  can_manage_store_receipts: '可管理店面收據',
  can_manage_ck_receipts: '可管理央廚收據',
  can_manage_ck_prices: '可管理央廚單價',
  can_review_closings: '可審核帳目',
  can_export_reports: '可匯出報表',
  error: '錯誤內容',
  source: '操作裝置',
  device: '裝置',
  browser: '瀏覽器',
  os: '作業系統',
  pre_dispute_snapshot: '退回前完整帳目',
  audit_version: '紀錄格式版本',
  reimbursement_adjustment: '補款調整金額',
  reimbursement_adjustment_note: '補款調整原因',
  deduct_from_reimbursement: '從央廚補款扣除',
  paid: '補款已送出',
  handoff_confirmed: '補款已點交',
  item_mapping_id: '品項設定編號',
  disabled_at: '停用時間',
  reactivated_at: '重新啟用時間',
  archived_at: '刪除時間',
  unavailable_from: '停止使用月份',
  available_from: '恢復使用月份',
  effective_at: '生效時間',
  explicit_item: '正式品項',
  history_preserved: '保留歷史帳目',
  historical_amounts_preserved: '保留歷史金額',
  sign_mode: '金額正負規則',
  is_negative: '固定負數',
  total_revenue: '營業額',
  total_cost: '總成本',
  total_expenses: '總支出',
  expected_remit: '應包金額',
  actual_remit: '實際包入',
  should_include_delivery: '應計配送金額',
  variance: '誤差',
  channel: '營收通路',
  account_name: '帳號名稱',
  gross_amount: '營收金額',
  is_cash: '是否為現金',
  category_id: '分類編號',
  order_no: '訂單編號',
  entered_by: '輸入人員',
  entered_at: '輸入時間',
  locked_at: '鎖定時間',
  edit_history: '修改紀錄',
  platform: '平台',
  input_amount: '輸入金額',
  ocr_amount: '照片辨識金額',
  ocr_vendor: '照片辨識廠商',
  ocr_date: '照片辨識日期',
  manual_amount: '人工輸入金額',
  diff: '差額',
  bills_1000: '一千元鈔票張數',
  bills_500: '五百元鈔票張數',
  bills_100: '一百元鈔票張數',
  coins_50: '五十元硬幣枚數',
  coins_10: '十元硬幣枚數',
  coins_5: '五元硬幣枚數',
  coins_1: '一元硬幣枚數',
  cash_total: '現金總額',
  photo_url: '照片',
  image_url: '圖片',
  created_at: '建立時間',
  updated_at: '更新時間',
  submitted_at: '送出時間',
  verified_at: '核准時間',
  disputed_at: '退回時間',
  disputed_by: '退回人員',
  dispute_note: '退回原因',
  sort_order: '排列順序',
}

const VALUE_LABELS: Record<string, string> = {
  draft: '草稿',
  submitted: '待審核',
  verified: '已核准',
  disputed: '已退回',
  info: '一般',
  warn: '警告',
  error: '錯誤',
  positive: '固定正數',
  negative: '固定負數',
  flexible: '每筆可切換正負',
  invoice: '統一發票',
  receipt: '收據',
  delivery_note: '估價單／送貨單',
  store_closing: '店面結帳資料',
  ck_daily_record: '央廚每日帳目',
  central_kitchen: '央廚',
  store: '店面',
  user: '管理人員',
  store_closing_photo: '店面結帳照片',
  update_settings: '修改設定',
  reimbursement_adjustment: '調整補款',
}

const CK_COMPARISON_FIELDS = ['status', 'member_orders', 'external_orders', 'expenses', 'receipt_photo_count'] as const

export function auditMetadataLabel(key: string) {
  return AUDIT_METADATA_LABELS[key] ?? '其他資料'
}

export function auditPrimitiveText(value: unknown) {
  if (value === null || value === undefined || value === '') return '—'
  if (typeof value === 'boolean') return value ? '是' : '否'
  if (typeof value === 'number') return Number.isFinite(value) ? value.toLocaleString('zh-TW') : String(value)
  if (typeof value === 'string') return VALUE_LABELS[value] ?? value
  return String(value)
}

/**
 * 舊版央廚操作軌跡只保存每次儲存後的內容；用同店同日期較早的紀錄補出差異。
 * 僅比較本次確實有保存的欄位，null 代表該次操作未更新，不可誤判為清空。
 */
export function deriveLegacyCKRecordChanges(
  current: Record<string, unknown>,
  olderRecords: Record<string, unknown>[],
): AuditChange[] {
  return CK_COMPARISON_FIELDS.flatMap(field => {
    const after = current[field]
    if (after === null || after === undefined) return []
    const older = olderRecords.find(record => record[field] !== null && record[field] !== undefined)
    const before = older?.[field] ?? null
    if (JSON.stringify(before) === JSON.stringify(after)) return []
    return [{ field, label: auditMetadataLabel(field), before, after }]
  })
}
